---
title: "Example Number Plugging"
author: "Grant Nguyen"
date: "10/20/2017"
runtime: shiny
output:
  html_document: null
resource_files:
- input_data/rmarkdown_data.rds
always_allow_html: yes
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(ggplot2)
library(plotly)
library(DT)
library(sparkline)
library(data.table)

## Pull GBD2015 global cycling deaths
# data <- get_outputs(topic = "cause", gbd_round_id = 3, location_id = "lvl3", year_id = c(1990, 1995, 2000, 2005, 2010, 2015), sex_id = c(1,2), cause_id = 691, metric_id = c(1,3))

data <- readRDS("input_data/rmarkdown_data.rds")

## Format numbers to uncertainty intervals, without rounding to a digit
## The gsub is used because format adds spaces in front of character values so that all output takes up the same digits. We don't want this.
format_num <- function(x) return(gsub(" ", "", format(round(x, 0), decimal.mark = ".", big.mark = ",")))
data[metric_name == "Number", ui_val := paste0(format_num(val), " (", format_num(lower), ", ", format_num(upper), ")")]

## Convert rate to rate per 100,000, display to three rounded digits
format_rate <- function(x) return(gsub(" ", "", format(round(x * 100000, 3), decimal.mark = ".", big.mark = ",")))
data[metric_name == "Rate", ui_val := paste0(format_rate(val), " (", format_rate(lower), ", ", format_rate(upper), ")")]
```

## Interactive Tables
You can also use packages to make your output #fancy. This table uses the sparkline package to add sparklines to the table.

```{r chn_death_formattable, echo = FALSE}
## Reshape to wide by deaths, and add sparklines
wide_data <- data[metric_name == "Number" & sex == "Male", list(year_id, location_name, val)]
wide_data[, year := as.character(paste0("Deaths ", year_id))]
wide_data[, year_id := NULL]
wide_data <- dcast(wide_data, location_name ~ year, value.var = "val")

## Create a comma-separated list of numbers, which will be fed into the sparkline
wide_data[, `Year Trend` := paste(`Deaths 1990`, `Deaths 1995`, `Deaths 2000`, `Deaths 2005`, `Deaths 2010`, `Deaths 2015`, sep = ",")]

setnames(wide_data, "location_name", "Country")

## Decide which column to feed to the sparkline data object called sparkSeries
col_defs <- list(list(targets = 7, render = JS("function(data, type, full){ return '<span class=spark>' + data + '</span>' }")))

## Decide how to format the sparkline display -- width in pixels
line_string <- "width:100, type: 'line', lineColor: 'black', fillColor: '#ccc', highlightLineColor: 'orange', highlightSpotColor: 'orange'"

## Create a sparkline based on the sparkSeries data object
myspark <- JS(paste0("function (oSettings, json) {\n  $('.spark:not(:has(canvas))').sparkline('html', { ", line_string, " })}"), collapse = "")

d1 <- datatable(wide_data, 
                rownames = FALSE, 
                options = list(columnDefs = col_defs, fnDrawCallback = myspark),
                filter=list(position="top",plain=T))
d1$dependencies <- append(d1$dependencies, htmlwidgets:::getDependency("sparkline"))
d1
```

## Interactive Plots

```{r top10_2010_deaths, echo = FALSE, warning = FALSE}
top10_2010_deaths_male <- data[year_id == 2010 & sex == "Male" & metric_name == "Number"]
setorder(top10_2010_deaths_male, -val)
top10_2010_deaths_male <- top10_2010_deaths_male[1:10]

top10_2010_deaths_female <- data[year_id == 2010 & sex == "Female" & metric_name == "Number"]
setorder(top10_2010_deaths_female, -val)
top10_2010_deaths_female <- top10_2010_deaths_female[1:10]
```

  
```{r top10_female_plot, echo=FALSE, warning = FALSE}
top10_changes_female <- data[location_name %in% unique(top10_2010_deaths_female$location_name) & sex == "Female" & metric_name == "Number"]
p <- ggplot(top10_changes_female) +
  geom_line(aes(x = year_id, y = val, color = location_name)) +
  xlab("Year") +
  ylab("Cyclist Deaths") +
  ggtitle("Total Female Cyclist Deaths: Top 10 Countries in 2010")
ggplotly(p)
```


```{r, top10_male_plot, echo=FALSE, warning = FALSE}
wide_data[, `Percent Change` := abs((`Deaths 2015` - `Deaths 1990`) / `Deaths 1990`)]
wide_data[, `Absolute Change` := (`Deaths 2015` - `Deaths 1990`)]

p <- ggplot(wide_data) +
  geom_point(aes(x = `Percent Change`, y = `Absolute Change`, color = Country)) +
  xlab("Absolute value of percent change from 1990 to 2015") +
  ylab("Absolute change from 1990 to 2015")
ggplotly(p)
```

## Shiny!

```{r, shiny_plot, echo=FALSE, warning = FALSE}
inputPanel(
  sliderInput("n_countries", label = "Number of countries:", min = 1, max = 50, value = 10, step = 1),
  radioButtons("num_rate", label = "Number or Rate", choices = c("Number", "Rate")),
  radioButtons("sel_sex", label = "Sex", choices = c("Female", "Male"))
)
renderPlotly({
  top_deaths_reactive <- data[year_id == 2015 & sex == input$sel_sex & metric_name == input$num_rate]
  
  setorder(top_deaths_reactive, -val)
  top_deaths_reactive <- top_deaths_reactive[1:input$n_countries]
  graph_dt <- data[location_name %in% unique(top_deaths_reactive$location_name) & sex == input$sel_sex & metric_name == input$num_rate]
  
  p <- ggplot(graph_dt) +
    geom_line(aes(x = year_id, y = val, color = location_name)) +
    xlab("Year") +
    ylab("Cyclist Deaths") +
    ggtitle(paste0("Countries with the top ", input$n_countries, " death ", input$num_rate, " for ", input$sel_sex, " in 2015"))
  ggplotly(p)
})

```
